language: node_js
node_js:
- '4.5'
env:
  global:
  - DEPLOY_BRANCH=master
  - secure: "1FaimSHlLI2lTZk+8rPlz+nnzDGAzAifHOwo1YxN7Q8v9jjtgP5wXrt1CXhUNE2zDUIS9hwHOizMoNrYqOAohv/rskadkhJD5uyTPLJ8Mk3FjrXUNViB1SZk8SZVM0+O7j0zxhwleaIT1TaCHurOLl37geCyog0D2rR19K5YrbSBWnGe0sLkBpz6hvCWjpnAhG1Si6fSogJBOE/mkTOOc5xzC2JQqKSCWN03C6N+fsCBGSyoROwwoAUJMDa39R5G3ecIlP7DspPxzbCpr4aKXlAqfu/gTxCWqW14nIeVmKG/M75twNE0e7buqlzaOTi1KpHyNAjJT0Q5smH0ncWO9w5hUjcQ1WpdpBMgUYXfoGkLs//+eG+AP6JjNzzgJvbPuSRlNP+lN0wSVft86Kopl+xGzHE988ALWAoUm6w8/BgrlEDNcBfJFpiDkXv9mZQr7HUkUsP29FiSzhXmEx4AtQcnJk6x8ZZ326gwM4RXgUHiJWYPx2mXjOaK2jCdVYw7+PvlWtvPgIcjaSteRN6xOQCpNYkWSGKqvlQyEmFzihfxmckixDzMRpZCNzFQWED9ZMGV48XJzhgF2wcv1wsaQGKMI5duZD0UQIyyvkbdqZKG6YRVuQxtrODu2te6iC2GqvsAQz3lUzCtisvCuvw31kVsmq7EQ3ZmVQ8H0B96PIA="
cache:
  directories:
  - node_modules
before_install:
- chmod +x ./.build_scripts/deploy.sh
- chmod +x ./.build_scripts/lint.sh
before_script:
- "./.build_scripts/lint.sh"
- npm test
script:
- bundle install
- npm run build
after_success:
- "./.build_scripts/deploy.sh"
