source: app
# To exclude inside app/
exclude:
  - assets/scripts
  - assets/styles
  - assets/graphics/collecticons
baseurl: http://landscape.satsummit.io
kramdown:
  input: GFM
  syntax_highlighter: rouge

collections:
  introduction:
    output: false